package com.paicbd.module.e2e;

public enum MtForwardSmReaction {
    RETURN_SUCCESS,
    ERROR_UNIDENTIFIED_SUBSCRIBER,
    ERROR_ABSENT_SUBSCRIBER_SM,
    ERROR_ILLEGAL_SUBSCRIBER,
    ERROR_ILLEGAL_EQUIPMENT,
    ERROR_FACILITY_NOT_SUPPORTED,
    ERROR_ABSENT_SUBSCRIBER,
    SUBSCRIBER_BUSY_FOR_MT_SMS,
    SM_DELIVERY_FAILURE,
    ERROR_SYSTEM_FAILURE,
    ERROR_SYSTEM_FAILURE_MEMORY_CAPACITY_EXCEEDED,
    ERROR_DATA_MISSING,
    ERROR_SYSTEM_FAILURE_UNKNOWN_SERVICE_CENTRE
}
