package com.paicbd.module.e2e;

public enum SendRoutingInfoForSmReaction {
    RETURN_SUCCESS,
    ERROR_UNKNOWN_SUBSCRIBER,
    ERROR_ABSENT_SUBSCRIBER_SM,
    ERROR_TELESERVICE_NOT_PROVISIONED,
    ERROR_CALL_BARRED,
    ERROR_FACILITY_NOT_SUPPORTED,
    ERROR_ABSENT_SUBSCRIBER,
    ERROR_SYSTEM_FAILURE,
    ERROR_DATA_MISSING,
    ERROR_UNEXPECTED_DATA_VALUE
}
